#!/bin/bash 

DEBUG=1 PORT=3333 ./server &
PID=$!

sleep 2s

[[ -f cache.json ]] && rm cache.json

curl -s -X GET   "http://0.0.0.0:3333/doc" > rest.txt
curl -X POST  "http://0.0.0.0:3333/scheduler" -H "Content-Type: application/json" -d '{"id":"foo","url":"http://www.google.com","method":"post","payload":{"foo":"bar"}}'
curl -X GET   "http://0.0.0.0:3333/scheduler" 
curl -X PUT   "http://0.0.0.0:3333/scheduler/trigger/foo"
sleep 2s
kill -9 $PID
